/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AppRouteImport } from "./routes/app"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PortalIndexRouteImport } from "./routes/portal.index"
import { Route as AppIndexRouteImport } from "./routes/app.index"
import { Route as RecoverTokenRouteImport } from "./routes/recover.$token"
import { Route as PortalTokenRouteImport } from "./routes/portal.$token"
import { Route as CheckoutSessionRouteImport } from "./routes/checkout.$session"
import { Route as AppWebhooksRouteImport } from "./routes/app.webhooks"
import { Route as AppSubscribersRouteImport } from "./routes/app.subscribers"
import { Route as AppPlansRouteImport } from "./routes/app.plans"
import { Route as AppInvoicesRouteImport } from "./routes/app.invoices"
import { Route as AppDunningRouteImport } from "./routes/app.dunning"
import { Route as AppBillingRouteImport } from "./routes/app.billing"
import { Route as AppApiKeysRouteImport } from "./routes/app.api-keys"
import { Route as AppProjectsIndexRouteImport } from "./routes/app.projects.index"
import { Route as AppSubscribersIdRouteImport } from "./routes/app.subscribers.$id"
import { Route as AppSettingsPayoutsRouteImport } from "./routes/app.settings.payouts"
import { Route as AppProjectsNewRouteImport } from "./routes/app.projects.new"

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: "/portal/",
  path: "/portal/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const RecoverTokenRoute = RecoverTokenRouteImport.update({
  id: "/recover/$token",
  path: "/recover/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: "/portal/$token",
  path: "/portal/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSessionRoute = CheckoutSessionRouteImport.update({
  id: "/checkout/$session",
  path: "/checkout/$session",
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhooksRoute = AppWebhooksRouteImport.update({
  id: "/webhooks",
  path: "/webhooks",
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersRoute = AppSubscribersRouteImport.update({
  id: "/subscribers",
  path: "/subscribers",
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: "/plans",
  path: "/plans",
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: "/invoices",
  path: "/invoices",
  getParentRoute: () => AppRoute,
} as any)
const AppDunningRoute = AppDunningRouteImport.update({
  id: "/dunning",
  path: "/dunning",
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: "/api-keys",
  path: "/api-keys",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersIdRoute = AppSubscribersIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => AppSubscribersRoute,
} as any)
const AppSettingsPayoutsRoute = AppSettingsPayoutsRouteImport.update({
  id: "/settings/payouts",
  path: "/settings/payouts",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: "/projects/new",
  path: "/projects/new",
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/app/api-keys": typeof AppApiKeysRoute
  "/app/billing": typeof AppBillingRoute
  "/app/dunning": typeof AppDunningRoute
  "/app/invoices": typeof AppInvoicesRoute
  "/app/plans": typeof AppPlansRoute
  "/app/subscribers": typeof AppSubscribersRouteWithChildren
  "/app/webhooks": typeof AppWebhooksRoute
  "/checkout/$session": typeof CheckoutSessionRoute
  "/portal/$token": typeof PortalTokenRoute
  "/recover/$token": typeof RecoverTokenRoute
  "/app/": typeof AppIndexRoute
  "/portal/": typeof PortalIndexRoute
  "/app/projects/new": typeof AppProjectsNewRoute
  "/app/settings/payouts": typeof AppSettingsPayoutsRoute
  "/app/subscribers/$id": typeof AppSubscribersIdRoute
  "/app/projects/": typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/app/api-keys": typeof AppApiKeysRoute
  "/app/billing": typeof AppBillingRoute
  "/app/dunning": typeof AppDunningRoute
  "/app/invoices": typeof AppInvoicesRoute
  "/app/plans": typeof AppPlansRoute
  "/app/subscribers": typeof AppSubscribersRouteWithChildren
  "/app/webhooks": typeof AppWebhooksRoute
  "/checkout/$session": typeof CheckoutSessionRoute
  "/portal/$token": typeof PortalTokenRoute
  "/recover/$token": typeof RecoverTokenRoute
  "/app": typeof AppIndexRoute
  "/portal": typeof PortalIndexRoute
  "/app/projects/new": typeof AppProjectsNewRoute
  "/app/settings/payouts": typeof AppSettingsPayoutsRoute
  "/app/subscribers/$id": typeof AppSubscribersIdRoute
  "/app/projects": typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/app/api-keys": typeof AppApiKeysRoute
  "/app/billing": typeof AppBillingRoute
  "/app/dunning": typeof AppDunningRoute
  "/app/invoices": typeof AppInvoicesRoute
  "/app/plans": typeof AppPlansRoute
  "/app/subscribers": typeof AppSubscribersRouteWithChildren
  "/app/webhooks": typeof AppWebhooksRoute
  "/checkout/$session": typeof CheckoutSessionRoute
  "/portal/$token": typeof PortalTokenRoute
  "/recover/$token": typeof RecoverTokenRoute
  "/app/": typeof AppIndexRoute
  "/portal/": typeof PortalIndexRoute
  "/app/projects/new": typeof AppProjectsNewRoute
  "/app/settings/payouts": typeof AppSettingsPayoutsRoute
  "/app/subscribers/$id": typeof AppSubscribersIdRoute
  "/app/projects/": typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/app"
    | "/login"
    | "/register"
    | "/app/api-keys"
    | "/app/billing"
    | "/app/dunning"
    | "/app/invoices"
    | "/app/plans"
    | "/app/subscribers"
    | "/app/webhooks"
    | "/checkout/$session"
    | "/portal/$token"
    | "/recover/$token"
    | "/app/"
    | "/portal/"
    | "/app/projects/new"
    | "/app/settings/payouts"
    | "/app/subscribers/$id"
    | "/app/projects/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/register"
    | "/app/api-keys"
    | "/app/billing"
    | "/app/dunning"
    | "/app/invoices"
    | "/app/plans"
    | "/app/subscribers"
    | "/app/webhooks"
    | "/checkout/$session"
    | "/portal/$token"
    | "/recover/$token"
    | "/app"
    | "/portal"
    | "/app/projects/new"
    | "/app/settings/payouts"
    | "/app/subscribers/$id"
    | "/app/projects"
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/login"
    | "/register"
    | "/app/api-keys"
    | "/app/billing"
    | "/app/dunning"
    | "/app/invoices"
    | "/app/plans"
    | "/app/subscribers"
    | "/app/webhooks"
    | "/checkout/$session"
    | "/portal/$token"
    | "/recover/$token"
    | "/app/"
    | "/portal/"
    | "/app/projects/new"
    | "/app/settings/payouts"
    | "/app/subscribers/$id"
    | "/app/projects/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CheckoutSessionRoute: typeof CheckoutSessionRoute
  PortalTokenRoute: typeof PortalTokenRoute
  RecoverTokenRoute: typeof RecoverTokenRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portal/": {
      id: "/portal/"
      path: "/portal"
      fullPath: "/portal/"
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/": {
      id: "/app/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/recover/$token": {
      id: "/recover/$token"
      path: "/recover/$token"
      fullPath: "/recover/$token"
      preLoaderRoute: typeof RecoverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portal/$token": {
      id: "/portal/$token"
      path: "/portal/$token"
      fullPath: "/portal/$token"
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/checkout/$session": {
      id: "/checkout/$session"
      path: "/checkout/$session"
      fullPath: "/checkout/$session"
      preLoaderRoute: typeof CheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/webhooks": {
      id: "/app/webhooks"
      path: "/webhooks"
      fullPath: "/app/webhooks"
      preLoaderRoute: typeof AppWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/subscribers": {
      id: "/app/subscribers"
      path: "/subscribers"
      fullPath: "/app/subscribers"
      preLoaderRoute: typeof AppSubscribersRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/plans": {
      id: "/app/plans"
      path: "/plans"
      fullPath: "/app/plans"
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/invoices": {
      id: "/app/invoices"
      path: "/invoices"
      fullPath: "/app/invoices"
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/dunning": {
      id: "/app/dunning"
      path: "/dunning"
      fullPath: "/app/dunning"
      preLoaderRoute: typeof AppDunningRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/billing": {
      id: "/app/billing"
      path: "/billing"
      fullPath: "/app/billing"
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/api-keys": {
      id: "/app/api-keys"
      path: "/api-keys"
      fullPath: "/app/api-keys"
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/projects/": {
      id: "/app/projects/"
      path: "/projects"
      fullPath: "/app/projects/"
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/subscribers/$id": {
      id: "/app/subscribers/$id"
      path: "/$id"
      fullPath: "/app/subscribers/$id"
      preLoaderRoute: typeof AppSubscribersIdRouteImport
      parentRoute: typeof AppSubscribersRoute
    }
    "/app/settings/payouts": {
      id: "/app/settings/payouts"
      path: "/settings/payouts"
      fullPath: "/app/settings/payouts"
      preLoaderRoute: typeof AppSettingsPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/projects/new": {
      id: "/app/projects/new"
      path: "/projects/new"
      fullPath: "/app/projects/new"
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSubscribersRouteChildren {
  AppSubscribersIdRoute: typeof AppSubscribersIdRoute
}

const AppSubscribersRouteChildren: AppSubscribersRouteChildren = {
  AppSubscribersIdRoute: AppSubscribersIdRoute,
}

const AppSubscribersRouteWithChildren = AppSubscribersRoute._addFileChildren(
  AppSubscribersRouteChildren,
)

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDunningRoute: typeof AppDunningRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPlansRoute: typeof AppPlansRoute
  AppSubscribersRoute: typeof AppSubscribersRouteWithChildren
  AppWebhooksRoute: typeof AppWebhooksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppSettingsPayoutsRoute: typeof AppSettingsPayoutsRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppBillingRoute: AppBillingRoute,
  AppDunningRoute: AppDunningRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPlansRoute: AppPlansRoute,
  AppSubscribersRoute: AppSubscribersRouteWithChildren,
  AppWebhooksRoute: AppWebhooksRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppSettingsPayoutsRoute: AppSettingsPayoutsRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CheckoutSessionRoute: CheckoutSessionRoute,
  PortalTokenRoute: PortalTokenRoute,
  RecoverTokenRoute: RecoverTokenRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
