/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AppRouteImport } from "./routes/app"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PortalIndexRouteImport } from "./routes/portal.index"
import { Route as AppIndexRouteImport } from "./routes/app.index"
import { Route as RecoverTokenRouteImport } from "./routes/recover.$token"
import { Route as PortalTokenRouteImport } from "./routes/portal.$token"
import { Route as CheckoutSessionRouteImport } from "./routes/checkout.$session"
import { Route as AppInvoicesRouteImport } from "./routes/app.invoices"
import { Route as AppProjectIdIndexRouteImport } from "./routes/app.$projectId.index"
import { Route as AppProjectIdWebhooksRouteImport } from "./routes/app.$projectId.webhooks"
import { Route as AppProjectIdPlansRouteImport } from "./routes/app.$projectId.plans"
import { Route as AppProjectIdDunningRouteImport } from "./routes/app.$projectId.dunning"
import { Route as AppProjectIdBillingRouteImport } from "./routes/app.$projectId.billing"
import { Route as AppProjectIdApiKeysRouteImport } from "./routes/app.$projectId.api-keys"
import { Route as AppProjectIdSubscribersIndexRouteImport } from "./routes/app.$projectId.subscribers.index"
import { Route as AppProjectIdSubscribersIdRouteImport } from "./routes/app.$projectId.subscribers.$id"
import { Route as AppProjectIdSettingsPayoutsRouteImport } from "./routes/app.$projectId.settings.payouts"

const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: "/portal/",
  path: "/portal/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const RecoverTokenRoute = RecoverTokenRouteImport.update({
  id: "/recover/$token",
  path: "/recover/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: "/portal/$token",
  path: "/portal/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSessionRoute = CheckoutSessionRouteImport.update({
  id: "/checkout/$session",
  path: "/checkout/$session",
  getParentRoute: () => rootRouteImport,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: "/invoices",
  path: "/invoices",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdIndexRoute = AppProjectIdIndexRouteImport.update({
  id: "/$projectId/",
  path: "/$projectId/",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdWebhooksRoute = AppProjectIdWebhooksRouteImport.update({
  id: "/$projectId/webhooks",
  path: "/$projectId/webhooks",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdPlansRoute = AppProjectIdPlansRouteImport.update({
  id: "/$projectId/plans",
  path: "/$projectId/plans",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdDunningRoute = AppProjectIdDunningRouteImport.update({
  id: "/$projectId/dunning",
  path: "/$projectId/dunning",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdBillingRoute = AppProjectIdBillingRouteImport.update({
  id: "/$projectId/billing",
  path: "/$projectId/billing",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdApiKeysRoute = AppProjectIdApiKeysRouteImport.update({
  id: "/$projectId/api-keys",
  path: "/$projectId/api-keys",
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdSubscribersIndexRoute =
  AppProjectIdSubscribersIndexRouteImport.update({
    id: "/$projectId/subscribers/",
    path: "/$projectId/subscribers/",
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectIdSubscribersIdRoute =
  AppProjectIdSubscribersIdRouteImport.update({
    id: "/$projectId/subscribers/$id",
    path: "/$projectId/subscribers/$id",
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectIdSettingsPayoutsRoute =
  AppProjectIdSettingsPayoutsRouteImport.update({
    id: "/$projectId/settings/payouts",
    path: "/$projectId/settings/payouts",
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/app/invoices": typeof AppInvoicesRoute
  "/checkout/$session": typeof CheckoutSessionRoute
  "/portal/$token": typeof PortalTokenRoute
  "/recover/$token": typeof RecoverTokenRoute
  "/app/": typeof AppIndexRoute
  "/portal/": typeof PortalIndexRoute
  "/app/$projectId/api-keys": typeof AppProjectIdApiKeysRoute
  "/app/$projectId/billing": typeof AppProjectIdBillingRoute
  "/app/$projectId/dunning": typeof AppProjectIdDunningRoute
  "/app/$projectId/plans": typeof AppProjectIdPlansRoute
  "/app/$projectId/webhooks": typeof AppProjectIdWebhooksRoute
  "/app/$projectId/": typeof AppProjectIdIndexRoute
  "/app/$projectId/settings/payouts": typeof AppProjectIdSettingsPayoutsRoute
  "/app/$projectId/subscribers/$id": typeof AppProjectIdSubscribersIdRoute
  "/app/$projectId/subscribers/": typeof AppProjectIdSubscribersIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/app/invoices": typeof AppInvoicesRoute
  "/checkout/$session": typeof CheckoutSessionRoute
  "/portal/$token": typeof PortalTokenRoute
  "/recover/$token": typeof RecoverTokenRoute
  "/app": typeof AppIndexRoute
  "/portal": typeof PortalIndexRoute
  "/app/$projectId/api-keys": typeof AppProjectIdApiKeysRoute
  "/app/$projectId/billing": typeof AppProjectIdBillingRoute
  "/app/$projectId/dunning": typeof AppProjectIdDunningRoute
  "/app/$projectId/plans": typeof AppProjectIdPlansRoute
  "/app/$projectId/webhooks": typeof AppProjectIdWebhooksRoute
  "/app/$projectId": typeof AppProjectIdIndexRoute
  "/app/$projectId/settings/payouts": typeof AppProjectIdSettingsPayoutsRoute
  "/app/$projectId/subscribers/$id": typeof AppProjectIdSubscribersIdRoute
  "/app/$projectId/subscribers": typeof AppProjectIdSubscribersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/app/invoices": typeof AppInvoicesRoute
  "/checkout/$session": typeof CheckoutSessionRoute
  "/portal/$token": typeof PortalTokenRoute
  "/recover/$token": typeof RecoverTokenRoute
  "/app/": typeof AppIndexRoute
  "/portal/": typeof PortalIndexRoute
  "/app/$projectId/api-keys": typeof AppProjectIdApiKeysRoute
  "/app/$projectId/billing": typeof AppProjectIdBillingRoute
  "/app/$projectId/dunning": typeof AppProjectIdDunningRoute
  "/app/$projectId/plans": typeof AppProjectIdPlansRoute
  "/app/$projectId/webhooks": typeof AppProjectIdWebhooksRoute
  "/app/$projectId/": typeof AppProjectIdIndexRoute
  "/app/$projectId/settings/payouts": typeof AppProjectIdSettingsPayoutsRoute
  "/app/$projectId/subscribers/$id": typeof AppProjectIdSubscribersIdRoute
  "/app/$projectId/subscribers/": typeof AppProjectIdSubscribersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/app"
    | "/login"
    | "/register"
    | "/app/invoices"
    | "/checkout/$session"
    | "/portal/$token"
    | "/recover/$token"
    | "/app/"
    | "/portal/"
    | "/app/$projectId/api-keys"
    | "/app/$projectId/billing"
    | "/app/$projectId/dunning"
    | "/app/$projectId/plans"
    | "/app/$projectId/webhooks"
    | "/app/$projectId/"
    | "/app/$projectId/settings/payouts"
    | "/app/$projectId/subscribers/$id"
    | "/app/$projectId/subscribers/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/register"
    | "/app/invoices"
    | "/checkout/$session"
    | "/portal/$token"
    | "/recover/$token"
    | "/app"
    | "/portal"
    | "/app/$projectId/api-keys"
    | "/app/$projectId/billing"
    | "/app/$projectId/dunning"
    | "/app/$projectId/plans"
    | "/app/$projectId/webhooks"
    | "/app/$projectId"
    | "/app/$projectId/settings/payouts"
    | "/app/$projectId/subscribers/$id"
    | "/app/$projectId/subscribers"
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/login"
    | "/register"
    | "/app/invoices"
    | "/checkout/$session"
    | "/portal/$token"
    | "/recover/$token"
    | "/app/"
    | "/portal/"
    | "/app/$projectId/api-keys"
    | "/app/$projectId/billing"
    | "/app/$projectId/dunning"
    | "/app/$projectId/plans"
    | "/app/$projectId/webhooks"
    | "/app/$projectId/"
    | "/app/$projectId/settings/payouts"
    | "/app/$projectId/subscribers/$id"
    | "/app/$projectId/subscribers/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CheckoutSessionRoute: typeof CheckoutSessionRoute
  PortalTokenRoute: typeof PortalTokenRoute
  RecoverTokenRoute: typeof RecoverTokenRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app": {
      id: "/app"
      path: "/app"
      fullPath: "/app"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portal/": {
      id: "/portal/"
      path: "/portal"
      fullPath: "/portal/"
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/": {
      id: "/app/"
      path: "/"
      fullPath: "/app/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/recover/$token": {
      id: "/recover/$token"
      path: "/recover/$token"
      fullPath: "/recover/$token"
      preLoaderRoute: typeof RecoverTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portal/$token": {
      id: "/portal/$token"
      path: "/portal/$token"
      fullPath: "/portal/$token"
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/checkout/$session": {
      id: "/checkout/$session"
      path: "/checkout/$session"
      fullPath: "/checkout/$session"
      preLoaderRoute: typeof CheckoutSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/app/invoices": {
      id: "/app/invoices"
      path: "/invoices"
      fullPath: "/app/invoices"
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/": {
      id: "/app/$projectId/"
      path: "/$projectId"
      fullPath: "/app/$projectId/"
      preLoaderRoute: typeof AppProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/webhooks": {
      id: "/app/$projectId/webhooks"
      path: "/$projectId/webhooks"
      fullPath: "/app/$projectId/webhooks"
      preLoaderRoute: typeof AppProjectIdWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/plans": {
      id: "/app/$projectId/plans"
      path: "/$projectId/plans"
      fullPath: "/app/$projectId/plans"
      preLoaderRoute: typeof AppProjectIdPlansRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/dunning": {
      id: "/app/$projectId/dunning"
      path: "/$projectId/dunning"
      fullPath: "/app/$projectId/dunning"
      preLoaderRoute: typeof AppProjectIdDunningRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/billing": {
      id: "/app/$projectId/billing"
      path: "/$projectId/billing"
      fullPath: "/app/$projectId/billing"
      preLoaderRoute: typeof AppProjectIdBillingRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/api-keys": {
      id: "/app/$projectId/api-keys"
      path: "/$projectId/api-keys"
      fullPath: "/app/$projectId/api-keys"
      preLoaderRoute: typeof AppProjectIdApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/subscribers/": {
      id: "/app/$projectId/subscribers/"
      path: "/$projectId/subscribers"
      fullPath: "/app/$projectId/subscribers/"
      preLoaderRoute: typeof AppProjectIdSubscribersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/subscribers/$id": {
      id: "/app/$projectId/subscribers/$id"
      path: "/$projectId/subscribers/$id"
      fullPath: "/app/$projectId/subscribers/$id"
      preLoaderRoute: typeof AppProjectIdSubscribersIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/app/$projectId/settings/payouts": {
      id: "/app/$projectId/settings/payouts"
      path: "/$projectId/settings/payouts"
      fullPath: "/app/$projectId/settings/payouts"
      preLoaderRoute: typeof AppProjectIdSettingsPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectIdApiKeysRoute: typeof AppProjectIdApiKeysRoute
  AppProjectIdBillingRoute: typeof AppProjectIdBillingRoute
  AppProjectIdDunningRoute: typeof AppProjectIdDunningRoute
  AppProjectIdPlansRoute: typeof AppProjectIdPlansRoute
  AppProjectIdWebhooksRoute: typeof AppProjectIdWebhooksRoute
  AppProjectIdIndexRoute: typeof AppProjectIdIndexRoute
  AppProjectIdSettingsPayoutsRoute: typeof AppProjectIdSettingsPayoutsRoute
  AppProjectIdSubscribersIdRoute: typeof AppProjectIdSubscribersIdRoute
  AppProjectIdSubscribersIndexRoute: typeof AppProjectIdSubscribersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInvoicesRoute: AppInvoicesRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectIdApiKeysRoute: AppProjectIdApiKeysRoute,
  AppProjectIdBillingRoute: AppProjectIdBillingRoute,
  AppProjectIdDunningRoute: AppProjectIdDunningRoute,
  AppProjectIdPlansRoute: AppProjectIdPlansRoute,
  AppProjectIdWebhooksRoute: AppProjectIdWebhooksRoute,
  AppProjectIdIndexRoute: AppProjectIdIndexRoute,
  AppProjectIdSettingsPayoutsRoute: AppProjectIdSettingsPayoutsRoute,
  AppProjectIdSubscribersIdRoute: AppProjectIdSubscribersIdRoute,
  AppProjectIdSubscribersIndexRoute: AppProjectIdSubscribersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CheckoutSessionRoute: CheckoutSessionRoute,
  PortalTokenRoute: PortalTokenRoute,
  RecoverTokenRoute: RecoverTokenRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
